#!/bin/sh
./clean

RPIIO="../libs/rpiio"
RPILCD="../libs/rpilcd"
COMMONOPTS="-Fu${RPIIO} -Fi${RPIIO} -Fu${RPILCD} -Fi${RPILCD} -Sd -XX"
FPC="fpc"

$FPC $COMMONOPTS lcdtest20x4.dpr
$FPC $COMMONOPTS lcdtest16x2.dpr
